# Used for local development only
version: "3.8"
services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./local-dev/db-data/:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
