DROP INDEX IF EXISTS tales_url;
DROP INDEX IF EXISTS tales_id;
DROP TABLE IF EXISTS tales CASCADE;

DROP TABLE IF EXISTS tags CASCADE;

DROP INDEX IF EXISTS tales_tags_tale_id;
DROP TABLE IF EXISTS tales_tags CASCADE;

DROP INDEX IF EXISTS users_tales_user_id;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS users_tales CASCADE;